[project]
name = "nl-food-inspections-api"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.112.1",
    "pdfplumber>=0.11.5",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
